Commits were not reflected in PT and git, hence committing again. [#63112276] changes done to remove the error 'no module named dagfunctions.py' changes in __init.py and citations.py
[#62818790] changes done to remove error
"AttributeError: 'module' object has no attribute 'ancestors'"

[#62818800] changes done to remove error
"AttributeError: 'module' object has no attribute 'descendants'"


Former-commit-id: 3e22d3fb1054181dc88480a457dee47b8bf94e2a [formerly 6b0e445d5ed42862b53384b498af8afbb6deb562]
Former-commit-id: af5d151c05a6cfeb0a2293ec9c03e1a2c2bd6ec8